server:
  port: 10010

spring:
  application:
    name: merchant-admin

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jx.merchantadmin.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
